// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using FrontToASP.DAL;

namespace FrontToASP.Migrations
{
    [DbContext(typeof(FrontEndASP))]
    partial class FrontEndASPModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApplication5.Models.CustomerComment", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<string>("Content")
                    .HasMaxLength(255);

                b.Property<string>("Header")
                    .HasMaxLength(150);

                b.HasKey("Id");

                b.ToTable("CustomerComments");
            });

            modelBuilder.Entity("WebApplication5.Models.CustomerCommentItems", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<string>("Comment")
                    .HasMaxLength(150);

                b.Property<string>("Image")
                    .HasMaxLength(255);

                b.Property<string>("ImageAlt")
                    .HasMaxLength(150);

                b.Property<string>("Name")
                    .HasMaxLength(255);

                b.Property<string>("Speciality")
                    .HasMaxLength(150);

                b.HasKey("Id");

                b.ToTable("CustomerCommentsItems");
            });

            modelBuilder.Entity("WebApplication5.Models.Product", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<string>("Description");

                b.Property<string>("Header");

                b.HasKey("Id");

                b.ToTable("Products");
            });

            modelBuilder.Entity("WebApplication5.Models.ProductItems", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<decimal>("DiscountPrice");

                b.Property<bool>("HasDiscount");

                b.Property<string>("Image");

                b.Property<string>("ImageAlt");

                b.Property<string>("Name");

                b.Property<decimal>("Price");

                b.Property<string>("Rating");

                b.HasKey("Id");

                b.ToTable("ProductItems");
            });
#pragma warning restore 612, 618
        }
    }
}
